# Usa una imagen base de Node.js
FROM node:22-alpine

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el package.json y package-lock.json (si lo tienes)
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de la aplicación al contenedor
COPY . .

# Expone el puerto en el que la app escucha (3003)
EXPOSE 3003

# Comando para iniciar la aplicación
CMD ["node", "index.js"]
