apiVersion: v1
kind: Service
metadata:
  name: hour-v2-service
  labels:
    app:  hour-v2
    version: v1   
spec:
  selector:
    app: hour-v2
    version: v1   
  ports:
  # - name: http-hora-a  
    - protocol: TCP
      port: 80         # Puerto interno del Service
      targetPort: 3003 # Redirige al puerto 3003 del contenedor
  # type: ClusterIP
